### ISSUE TITLE
0.5 show error

### ISSUE THREAD

**Issue by dlfivefifty** [SimonDanisch/FixedSizeArrays.jl#137] opened 2016-07-02 09:37 UTC
``` julia
julia> Vec(0.,0.)
Vec(0.0Error showing value of type FixedSizeArrays.Vec{2,Float64}:
ERROR: MethodError: no method matching colon(::Int64, ::Type{Any})
Closest candidates are:
  colon{T<:Real}(::T<:Real, ::Any, ::T<:Real)
  colon{A<:Real,C<:Real}(::A<:Real, ::Any, ::C<:Real)
  colon{T}(::T, ::Any, ::T)
  ...
 in show(::IOContext{Base.Terminals.TTYTerminal}, ::FixedSizeArrays.Vec{2,Float64}) at /Users/solver/.julia/v0.5/FixedSizeArrays/src/FixedSizeArrays.jl:62
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::FixedSizeArrays.Vec{2,Float64}) at ./REPL.jl:114
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::FixedSizeArrays.Vec{2,Float64}) at ./REPL.jl:117
 in display(::FixedSizeArrays.Vec{2,Float64}) at ./multimedia.jl:143
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:134
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:121
 in (::Base.REPL.##18#19{Bool,Base.REPL.##29#38{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:631
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1570
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:882
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##598#599) at ./REPL.jl:167
 in _start() at ./client.jl:364
```

**Comment by c42f** [comment] 2016-07-12 13:45
This is more or less a duplicate of #137, aka FixedSizesArrays is completely broken (again) in 0.5

**Closed as completed by c42f** 2016-07-12 13:45 UTC
